# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bbUtlxwLV_TRP7jwv1E5CFzq5LPPhFw
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import joblib

# Load dataset
df = pd.read_csv("Crop_recommendation.csv")

# Split features and target
X = df.drop("label", axis=1)
y = df["label"]

# Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

# Train model
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

# Save files
joblib.dump(rf, "random_forest_model.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")

rf_model = joblib.load(
    "random_forest_model.pkl"
)

label_encoder = joblib.load(
    "label_encoder.pkl"
)

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import joblib

app = FastAPI(title="Crop Recommendation API")

# Load model and label encoder
try:
    rf_model = joblib.load("random_forest_model.pkl")
    label_encoder = joblib.load("label_encoder.pkl")

    if not hasattr(rf_model, "classes_"):
        rf_model = None
        print("Model loaded but it is NOT trained/fitted.")

except Exception as e:
    rf_model = None
    label_encoder = None
    print("Loading error:", e)

class SoilData(BaseModel):
    N: float
    P: float
    K: float
    temperature: float
    humidity: float
    ph: float
    rainfall: float

@app.get("/")
def home():
    return {
        "status": "Online",
        "model_loaded": rf_model is not None,
        "encoder_loaded": label_encoder is not None,
        "message": "Use /predict_rf for crop prediction"
    }

@app.post("/predict_rf")
def predict_rf(data: SoilData):

    if rf_model is None or label_encoder is None:
        raise HTTPException(
            status_code=500,
            detail="Model or label encoder not loaded."
        )

    try:
        input_data = [[
            data.N,
            data.P,
            data.K,
            data.temperature,
            data.humidity,
            data.ph,
            data.rainfall
        ]]

        prediction = rf_model.predict(input_data)[0]

        crop_name = label_encoder.inverse_transform(
            [prediction]
        )[0]

        return {
            "prediction": str(crop_name),
            "model": "Random Forest"
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=str(e)
        )